"""
app/schemas/notification_schema.py — Notification & AI Response Schemas

COVERS (Doc2 — Section 3.11, 3.12):
  GET  /notifications          → list[NotificationResponse]
  POST /notifications/{id}/read → NotificationResponse
  POST /notifications/read-all → { message, count }
  GET  /notifications/check    → NotificationCheckResult

  POST /ai/insights            → AIInsightRequest → AIInsightResponse
  GET  /ai/insights            → list[AIInsightResponse]
  POST /ai/chat                → AIChatRequest → AIChatResponse
  GET  /ai/chat/sessions       → list[AIChatSessionResponse]
  GET  /ai/chat/sessions/{id}  → AIChatSessionResponse

AI DESIGN (Doc1 — Section 6.1, Doc4 — Section 5.4):
  Insights are generated by Gemini, stored in DB, cached in Redis.
  They are expensive to generate — serve from cache until expires_at.
  User can force regeneration by calling POST /ai/insights again.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


# ── Notifications ──────────────────────────────────────────────────────────────

class NotificationResponse(BaseModel):
    """Single notification as returned by the API."""

    model_config = {"from_attributes": True}

    id: uuid.UUID
    user_id: uuid.UUID
    notification_type: str  # "BUDGET_EXCEEDED", "MIN_BALANCE", "FD_MATURITY", etc.
    title: str
    message: str
    metadata_: dict[str, Any] | None = None  # Extra context for rich rendering
    is_read: bool
    read_at: datetime | None
    created_at: datetime


class NotificationCheckResult(BaseModel):
    """
    GET /notifications/check — runs all alert checks.
    Returns a summary of what was checked and what was created.
    """

    checks_run: int
    notifications_created: int


class NotificationFilter(BaseModel):
    """Query params for GET /notifications."""

    is_read: bool | None = None  # None = all, False = unread only, True = read only
    limit: int = Field(20, ge=1, le=100)
    page: int = Field(1, ge=1)


# ── AI Insights ────────────────────────────────────────────────────────────────

class AIInsightRequest(BaseModel):
    """
    POST /ai/insights — generate or retrieve an insight.

    insight_type controls what Gemini analyses:
      MONTHLY_SUMMARY   → full breakdown of a specific month
      YEARLY_ANALYSIS   → patterns across the full year
      SAVINGS_TIPS      → personalised saving recommendations
      SPENDING_PATTERN  → day-of-week and category patterns

    period_month / period_year determine which data is analysed.
    If they match a cached insight that hasn't expired, the cached
    version is returned immediately (no Gemini call).
    """

    insight_type: str = Field(
        ...,
        description="MONTHLY_SUMMARY | YEARLY_ANALYSIS | SAVINGS_TIPS | SPENDING_PATTERN",
    )
    period_month: int | None = Field(None, ge=1, le=12)
    period_year: int | None = Field(None, ge=2020, le=2100)


class AIInsightResponse(BaseModel):
    """Returned by POST /ai/insights and GET /ai/insights."""

    model_config = {"from_attributes": True}

    id: uuid.UUID
    insight_type: str
    content: str  # Plain text insight from Gemini
    input_summary: dict[str, Any] | None  # What data was sent to Gemini
    expires_at: datetime
    tokens_used: int | None
    generated_at: datetime

    @property
    def is_fresh(self) -> bool:
        """True if the insight hasn't expired yet."""
        from datetime import timezone
        return datetime.now(timezone.utc) < self.expires_at


# ── AI Chat ────────────────────────────────────────────────────────────────────

class AIChatRequest(BaseModel):
    """POST /ai/chat — send a message to the AI assistant."""

    message: str = Field(..., min_length=1, max_length=2000)
    session_id: uuid.UUID | None = Field(
        None,
        description="Continue an existing session. Omit to start a new one.",
    )


class AIChatResponse(BaseModel):
    """Reply from the AI chat endpoint."""

    reply: str
    session_id: uuid.UUID  # Always returned so frontend can continue the session


class ChatMessage(BaseModel):
    """One message in a chat session history."""

    role: str  # "user" | "model"
    content: str
    timestamp: str


class AIChatSessionResponse(BaseModel):
    """Full chat session with message history."""

    model_config = {"from_attributes": True}

    id: uuid.UUID
    title: str | None
    history: list[dict[str, Any]]  # [{role, content, timestamp}]
    is_active: bool
    total_tokens_used: int | None
    created_at: datetime
    updated_at: datetime