"""
app/models/base.py — Shared ORM Base & Common Columns

WHY THIS FILE EXISTS:
  Every table in FinanceFlow has:
    - id: UUID primary key (not integer — see reason below)
    - created_at: when the row was first inserted
    - updated_at: auto-updated on every change via DB trigger

  Instead of copy-pasting these columns into 18 models, we define them
  once in a mixin and every model inherits them.

WHY UUID INSTEAD OF SERIAL/AUTO-INCREMENT (from Doc1 — Schema notes):
  Integer IDs are predictable: user with id=1, id=2, id=3...
  An attacker who knows your expense ID is "42" can guess "41" and "43".
  UUID is random: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
  There's no "next" UUID to guess. This is BOLA/IDOR prevention at the
  data model level (Video 20 — Security).

  Also: if we ever shard the DB or merge datasets, UUIDs don't collide.
  Two shards can both independently create IDs with zero coordination.

WHY server_default=func.gen_random_uuid():
  The UUID is generated by POSTGRES, not by Python. This means:
    1. The ID exists even before our Python code sees the row
    2. Bulk inserts via raw SQL also get correct UUIDs
    3. ID generation is consistent regardless of which app instance runs

UPDATED_AT STRATEGY:
  We use a PostgreSQL TRIGGER (defined in migration) that fires BEFORE
  every UPDATE and sets updated_at = NOW(). This is more reliable than
  doing it in Python — even manual SQL updates via psql get the right
  updated_at. The onupdate= in SQLAlchemy is a Python-layer fallback.
"""

import uuid
from datetime import datetime
from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    Declarative base for all ORM models.

    All models inherit from this. It holds the metadata (table registry)
    that Alembic reads for migration generation.
    """
    pass


class TimestampMixin:
    """
    Mixin that adds id, created_at, updated_at to any model.

    Usage:
        class Expense(TimestampMixin, Base):
            __tablename__ = "expenses"
            ...
            # Automatically gets: id, created_at, updated_at

    COLUMN TYPES:
      id:
        - UUID (PostgreSQL native type, 16 bytes, random)
        - Primary key, generated by Postgres (gen_random_uuid())
        - Never expose sequential IDs to clients

      created_at:
        - TIMESTAMPTZ (timestamp WITH time zone)
        - Set once on INSERT, never updated
        - server_default: Postgres sets it, not Python
        - Why TIMESTAMPTZ: stores offset-aware timestamps
          Pure TIMESTAMP ignores timezone — wrong for IST users

      updated_at:
        - TIMESTAMPTZ, updates on every change
        - server_default: same as created_at on first insert
        - onupdate: Python-layer update (fallback if trigger is missing)
        - Primary update happens via DB trigger in migration
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        # Why not default=uuid.uuid4: server_default lets Postgres generate
        # the UUID. Python default generates it in app memory — both work,
        # but server_default is more reliable for bulk inserts and migrations.
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        # onupdate: Python updates this when session.commit() is called
        # The DB trigger is the authoritative mechanism — this is the fallback
        onupdate=func.now(),
        nullable=False,
    )

    def __repr__(self) -> str:
        """
        Default repr for all models — shows table + id.
        Example: <Expense id=f47ac10b-58cc-...>
        Useful in debug logs and REPL sessions.
        """
        return f"<{self.__class__.__name__} id={self.id}>"